# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\"B\n\rResultMessage\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x17\n\x03\x41\x63k\x12\x10\n\x08received\x18\x01 \x01(\x08\x32=\n\x15\x43heckoutResultService\x12$\n\x0cReportResult\x12\x0e.ResultMessage\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESULTMESSAGE']._serialized_start=22
  _globals['_RESULTMESSAGE']._serialized_end=88
  _globals['_ACK']._serialized_start=90
  _globals['_ACK']._serialized_end=113
  _globals['_CHECKOUTRESULTSERVICE']._serialized_start=115
  _globals['_CHECKOUTRESULTSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
