# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orchestrator_pb2 as orchestrator__pb2


class CheckoutResultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportResult = channel.unary_unary(
                '/CheckoutResultService/ReportResult',
                request_serializer=orchestrator__pb2.CheckoutResult.SerializeToString,
                response_deserializer=orchestrator__pb2.Ack.FromString,
                )


class CheckoutResultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckoutResultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=orchestrator__pb2.CheckoutResult.FromString,
                    response_serializer=orchestrator__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CheckoutResultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckoutResultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CheckoutResultService/ReportResult',
            orchestrator__pb2.CheckoutResult.SerializeToString,
            orchestrator__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
