# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0cverification\"\x1f\n\x11InitOrderResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1b\n\rVerifyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x87\x02\n\tOrderData\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.verification.User\x12,\n\ncreditCard\x18\x02 \x01(\x0b\x32\x18.verification.CreditCard\x12\x13\n\x0buserComment\x18\x03 \x01(\t\x12!\n\x05items\x18\x04 \x03(\x0b\x32\x12.verification.Item\x12-\n\x0e\x62illingAddress\x18\x05 \x01(\x0b\x32\x15.verification.Address\x12\x16\n\x0eshippingMethod\x18\x06 \x01(\t\x12\x14\n\x0cgiftWrapping\x18\x07 \x01(\x08\x12\x15\n\rtermsAccepted\x18\x08 \x01(\x08\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"C\n\x0eVerifyResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"F\n\x10InitOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x05order\x18\x02 \x01(\x0b\x32\x17.verification.OrderData2\xa8\x01\n\x13VerificationService\x12\x43\n\x06Verify\x12\x1b.verification.VerifyRequest\x1a\x1c.verification.VerifyResponse\x12L\n\tInitOrder\x12\x1e.verification.InitOrderRequest\x1a\x1f.verification.InitOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITORDERRESPONSE']._serialized_start=48
  _globals['_INITORDERRESPONSE']._serialized_end=79
  _globals['_VERIFYREQUEST']._serialized_start=81
  _globals['_VERIFYREQUEST']._serialized_end=108
  _globals['_ORDERDATA']._serialized_start=111
  _globals['_ORDERDATA']._serialized_end=374
  _globals['_USER']._serialized_start=376
  _globals['_USER']._serialized_end=413
  _globals['_CREDITCARD']._serialized_start=415
  _globals['_CREDITCARD']._serialized_end=480
  _globals['_ITEM']._serialized_start=482
  _globals['_ITEM']._serialized_end=520
  _globals['_ADDRESS']._serialized_start=522
  _globals['_ADDRESS']._serialized_end=606
  _globals['_VERIFYRESPONSE']._serialized_start=608
  _globals['_VERIFYRESPONSE']._serialized_end=675
  _globals['_INITORDERREQUEST']._serialized_start=677
  _globals['_INITORDERREQUEST']._serialized_end=747
  _globals['_VERIFICATIONSERVICE']._serialized_start=750
  _globals['_VERIFICATIONSERVICE']._serialized_end=918
# @@protoc_insertion_point(module_scope)
