# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestion.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10suggestion.proto\x12\nsuggestion\"+\n\x08\x42ookList\x12\x1f\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x10.suggestion.Book\"5\n\x04\x42ook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2O\n\x11SuggestionService\x12:\n\x0cSuggestBooks\x12\x14.suggestion.BookList\x1a\x14.suggestion.BookListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKLIST']._serialized_start=32
  _globals['_BOOKLIST']._serialized_end=75
  _globals['_BOOK']._serialized_start=77
  _globals['_BOOK']._serialized_end=130
  _globals['_SUGGESTIONSERVICE']._serialized_start=132
  _globals['_SUGGESTIONSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
